#     _                     _           _     _   ____    _                 _   _
#    / \    __  __   ___   | |   ___   | |_  | | / ___|  | |_   _   _    __| | (_)   ___
#   / _ \   \ \/ /  / _ \  | |  / _ \  | __| | | \___ \  | __| | | | |  / _` | | |  / _ \
#  / ___ \   >  <  | (_) | | | | (_) | | |_  | |  ___) | | |_  | |_| | | (_| | | | | (_) |
# /_/  Dev. by \_\  \___/  |_|  \___/   \__| |_| |____/   \__|  \__,_vk.com/AxoStudio___/
# vk.com/pingisjoin (AxieFeat)
# Плагин является разработкой и собственностью AxolotlStudio (https://vk.com/AxoStudio)
# По поводу багов/ошибок писать сюда -> https://vk.me/pingisjoin
# Разработано для LifeCraft 2022

database:
  enabled: false # false - Выключена, true - Включена..
  system: "MySQL" #Только MySQL в данный момент, не меняйте это значение..
  host: "localhost" #Хост..
  database-name: "AxoDev" #Название базы данных..
  port: 3306 #3306 стандартный порт..
  username: "" #Ваше MySQL имя..
  password: "" #Ваш MySQL пароль..
  setup: true

#---------------------------------------
#               ВК-бот
#---------------------------------------

Lang: ru_RU #Смена языка

Chats: # Разрешенные чаты...
  - '1'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '15'
  - '16'

LogChat: 13 # В каком чате логировать действия
AlertChat: 15 # В каком чате отправлять предупреждения о проблемах
MainChat: 1 # Основной чат
AdminChat: 1 #Админ чат

Admins: #У кого есть полный доступ к боту
  - '613258536'
  - '528290750'
  - '298777487'

Moders: #У кого есть доступ к ркон
  - '0'

Managers: #У кого есть доступ к варнам
  - '566896388'

Reasons:
  - "hacks"

#---------------------------------------
#              Репорты
#---------------------------------------

Messages:
  Usage: "/report <ник> <причина>"
  Reported: "Вы отправили жалобу на игрока %player%"
  OnlyPlayer: "Эта команда для игроков!"
  Offline: "Игрок не найден"
  UsageCoolDown: 120
  СoolDown: "Вы слишком часто отправляете жалобы!"
  AlredyReported: "Вы уже отправили жалобу на %player%!"
  Self: "Вы не можете отравить жалобу на себя!"
  Notify: "Новый репорт на игрока %player_1%(%count%) от %player_2%. Причина: %reason%"
  Error: "Произошла ошибка! Сообщите Администрации."

#---------------------------------------
#              Слежка
#---------------------------------------

Usage: "/watch <ник>"
NotWatch: "Вы не в режиме слежки!"
Self: "Вы не можете следить за собой!"